[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
board_build.flash_size = 4MB

lib_deps =
  tzapu/WiFiManager@^2.0.17
  knolleary/PubSubClient@^2.8
  miguelbalboa/MFRC522@^1.4.11
  bblanchon/ArduinoJson@^7.0.4
